In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
import numpy as np

In [5]:
tf.set_random_seed(777)

In [10]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step  % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)
        
print("Your score will be", sess.run(hypothesis, feed_dict = {X:[[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis, feed_dict = {X: [[60,70,110],[90,100,80]]}))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost: 68479.24 
Prediction:
 [[ -96.46343 ]
 [-109.81928 ]
 [-111.79769 ]
 [-119.038536]
 [ -84.00308 ]
 [ -56.08633 ]
 [ -86.056404]
 [ -59.935307]
 [ -97.40455 ]
 [ -83.02706 ]
 [ -83.865944]
 [ -78.64712 ]
 [-118.44631 ]
 [-101.81907 ]
 [ -85.158585]
 [-109.30164 ]
 [ -98.36591 ]
 [-103.39904 ]
 [-114.2934  ]
 [-102.214226

310 Cost: 15.960044 
Prediction:
 [[150.00531]
 [185.67816]
 [179.75713]
 [198.27483]
 [141.35378]
 [109.64677]
 [151.35458]
 [115.936  ]
 [178.32912]
 [171.83488]
 [144.86574]
 [146.48131]
 [182.9742 ]
 [149.00307]
 [153.21037]
 [190.42468]
 [140.53835]
 [181.55411]
 [173.21487]
 [155.07819]
 [176.9811 ]
 [176.59346]
 [167.57544]
 [144.99788]
 [190.16377]]
320 Cost: 15.876927 
Prediction:
 [[150.01895 ]
 [185.67245 ]
 [179.76341 ]
 [198.27533 ]
 [141.34918 ]
 [109.630974]
 [151.3517  ]
 [115.92997 ]
 [178.3109  ]
 [171.80199 ]
 [144.86292 ]
 [146.46632 ]
 [182.98683 ]
 [149.02116 ]
 [153.20348 ]
 [190.41489 ]
 [140.55643 ]
 [181.55177 ]
 [173.23131 ]
 [155.09413 ]
 [176.97682 ]
 [176.58333 ]
 [167.57503 ]
 [145.02597 ]
 [190.16432 ]]
330 Cost: 15.794542 
Prediction:
 [[150.03253]
 [185.66676]
 [179.76968]
 [198.27582]
 [141.34457]
 [109.61525]
 [151.34883]
 [115.92398]
 [178.29277]
 [171.76923]
 [144.86008]
 [146.4514 ]
 [182.99939]
 [149.03915]
 [153.19661]
 [190.40512]
 [140.5744 ]


570 Cost: 14.021717 
Prediction:
 [[150.34122 ]
 [185.53775 ]
 [179.91208 ]
 [198.28734 ]
 [141.2402  ]
 [109.258026]
 [151.28403 ]
 [115.78811 ]
 [177.8806  ]
 [171.02519 ]
 [144.796   ]
 [146.11243 ]
 [183.28474 ]
 [149.4479  ]
 [153.04088 ]
 [190.18353 ]
 [140.98282 ]
 [181.49701 ]
 [173.61955 ]
 [155.47073 ]
 [176.87598 ]
 [176.34396 ]
 [167.56587 ]
 [145.68922 ]
 [190.17732 ]]
580 Cost: 13.955732 
Prediction:
 [[150.3534  ]
 [185.53267 ]
 [179.91771 ]
 [198.2878  ]
 [141.23611 ]
 [109.24395 ]
 [151.28148 ]
 [115.782776]
 [177.86436 ]
 [170.99588 ]
 [144.79349 ]
 [146.09909 ]
 [183.29599 ]
 [149.46402 ]
 [153.03476 ]
 [190.17482 ]
 [140.99892 ]
 [181.49496 ]
 [173.6342  ]
 [155.48495 ]
 [176.8722  ]
 [176.33493 ]
 [167.56554 ]
 [145.71426 ]
 [190.17783 ]]
590 Cost: 13.890356 
Prediction:
 [[150.3655  ]
 [185.5276  ]
 [179.92328 ]
 [198.28825 ]
 [141.232   ]
 [109.229935]
 [151.27895 ]
 [115.77745 ]
 [177.84819 ]
 [170.96669 ]
 [144.79097 ]
 [146.08577 ]
 [183.30717 ]
 [149.48003 ]


870 Cost: 12.276673 
Prediction:
 [[150.68379]
 [185.39433]
 [180.07   ]
 [198.30022]
 [141.12393]
 [108.86157]
 [151.21257]
 [115.63828]
 [177.4232 ]
 [170.19997]
 [144.72507]
 [145.73637]
 [183.60106]
 [149.90088]
 [152.86855]
 [189.93764]
 [141.43507]
 [181.43965]
 [174.0319 ]
 [155.87082]
 [176.76926]
 [176.08957]
 [167.55653]
 [146.39369]
 [190.19083]]
880 Cost: 12.226141 
Prediction:
 [[150.69446]
 [185.38988]
 [180.07494]
 [198.30064]
 [141.12032]
 [108.84924]
 [151.21037]
 [115.63365]
 [177.40898]
 [170.1743 ]
 [144.72287]
 [145.72469]
 [183.61089]
 [149.91496]
 [152.86319]
 [189.93001]
 [141.44911]
 [181.4379 ]
 [174.04472]
 [155.88326]
 [176.76596]
 [176.08165]
 [167.55626]
 [146.4156 ]
 [190.19127]]
890 Cost: 12.17606 
Prediction:
 [[150.70506]
 [185.3854 ]
 [180.07979]
 [198.30103]
 [141.11668]
 [108.83696]
 [151.20815]
 [115.62901]
 [177.39479]
 [170.14873]
 [144.72064]
 [145.71301]
 [183.62067]
 [149.92896]
 [152.85785]
 [189.92236]
 [141.46309]
 [181.4361 ]
 [174.05746]


1190 Cost: 10.862999 
Prediction:
 [[151.00252 ]
 [185.26064 ]
 [180.2168  ]
 [198.31236 ]
 [141.01521 ]
 [108.49271 ]
 [151.14665 ]
 [115.499954]
 [176.99767 ]
 [169.43277 ]
 [144.65923 ]
 [145.38664 ]
 [183.89491 ]
 [150.32152 ]
 [152.70876 ]
 [189.70888 ]
 [141.85466 ]
 [181.38719 ]
 [174.41512 ]
 [156.24274 ]
 [176.67052 ]
 [175.85292 ]
 [167.5483  ]
 [147.04845 ]
 [190.20305 ]]
1200 Cost: 10.824981 
Prediction:
 [[151.01178 ]
 [185.25676 ]
 [180.22105 ]
 [198.31271 ]
 [141.01207 ]
 [108.481995]
 [151.14476 ]
 [115.49596 ]
 [176.98532 ]
 [169.4105  ]
 [144.6573  ]
 [145.3765  ]
 [183.90346 ]
 [150.33372 ]
 [152.70412 ]
 [189.70224 ]
 [141.8668  ]
 [181.3857  ]
 [174.42624 ]
 [156.25352 ]
 [176.66765 ]
 [175.84605 ]
 [167.54805 ]
 [147.06743 ]
 [190.20341 ]]
1210 Cost: 10.78729 
Prediction:
 [[151.02101]
 [185.2529 ]
 [180.22531]
 [198.31308]
 [141.00893]
 [108.47134]
 [151.14287]
 [115.49198]
 [176.97304]
 [169.38837]
 [144.65541]
 [145.36641]
 [183.91194]
 [150.34587]
 [152.69952]

1620 Cost: 9.498072 
Prediction:
 [[151.36577 ]
 [185.10791 ]
 [180.3839  ]
 [198.3264  ]
 [140.8906  ]
 [108.072296]
 [151.07237 ]
 [115.34388 ]
 [176.51277 ]
 [168.55934 ]
 [144.58444 ]
 [144.98831 ]
 [184.2292  ]
 [150.79979 ]
 [152.52745 ]
 [189.44824 ]
 [142.33115 ]
 [181.3288  ]
 [174.85127 ]
 [156.66618 ]
 [176.55878 ]
 [175.58328 ]
 [167.53957 ]
 [147.79367 ]
 [190.21648 ]]
1630 Cost: 9.4721155 
Prediction:
 [[151.37343]
 [185.10469]
 [180.38742]
 [198.32669]
 [140.88797]
 [108.06344]
 [151.07082]
 [115.34061]
 [176.50255]
 [168.54094]
 [144.58287]
 [144.97992]
 [184.23625]
 [150.80986]
 [152.52367]
 [189.44276]
 [142.34117]
 [181.32759]
 [174.86047]
 [156.6751 ]
 [176.55644]
 [175.57762]
 [167.5394 ]
 [147.80937]
 [190.21675]]
1640 Cost: 9.446401 
Prediction:
 [[151.38104]
 [185.10149]
 [180.39093]
 [198.32698]
 [140.88533]
 [108.05462]
 [151.06926]
 [115.33736]
 [176.49237]
 [168.52263]
 [144.58131]
 [144.97157]
 [184.24327]
 [150.81987]
 [152.51987]
 [189.43727]
 [142.35115]

1990 Cost: 8.676223 
Prediction:
 [[151.6277  ]
 [184.9975  ]
 [180.50424 ]
 [198.3367  ]
 [140.80011 ]
 [107.769135]
 [151.01949 ]
 [115.23264 ]
 [176.16315 ]
 [167.93025 ]
 [144.53073 ]
 [144.70126 ]
 [184.46976 ]
 [151.1437  ]
 [152.39743 ]
 [189.26035 ]
 [142.67331 ]
 [181.28784 ]
 [175.1653  ]
 [156.97116 ]
 [176.47887 ]
 [175.38892 ]
 [167.53384 ]
 [148.33025 ]
 [190.22574 ]]
2000 Cost: 8.657536 
Prediction:
 [[151.6342  ]
 [184.99475 ]
 [180.50723 ]
 [198.33694 ]
 [140.79785 ]
 [107.761604]
 [151.01819 ]
 [115.229904]
 [176.15446 ]
 [167.91464 ]
 [144.5294  ]
 [144.69415 ]
 [184.47574 ]
 [151.15222 ]
 [152.3942  ]
 [189.25568 ]
 [142.6818  ]
 [181.28683 ]
 [175.1731  ]
 [156.97871 ]
 [176.4769  ]
 [175.3841  ]
 [167.53372 ]
 [148.34355 ]
 [190.22598 ]]
Your score will be [[192.61244]]
Other scores will be  [[190.10739]
 [170.40045]]
