In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [6]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _= sess.run([cost, hypothesis, train],
                                 feed_dict = {x1 : x1_data, x2 :  x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)
        

0 Cost: 109178.3 
Prediction:
 [-139.85912 -168.64272 -165.67021 -184.59158 -125.03696]
10 Cost: 3.9859614 
Prediction:
 [152.43213 182.67128 180.48451 192.36319 142.92682]
20 Cost: 2.98498 
Prediction:
 [153.31555 183.73482 181.53146 193.50427 143.73767]
30 Cost: 2.9834807 
Prediction:
 [153.31726 183.73863 181.53423 193.50821 143.7402 ]
40 Cost: 2.9819791 
Prediction:
 [153.3163  183.73921 181.53384 193.50874 143.7403 ]
50 Cost: 2.9804924 
Prediction:
 [153.31535 183.73979 181.53345 193.50926 143.74039]
60 Cost: 2.9790132 
Prediction:
 [153.31439 183.74037 181.53305 193.50977 143.74048]
70 Cost: 2.9775138 
Prediction:
 [153.31343 183.74095 181.53265 193.51027 143.74054]
80 Cost: 2.9760115 
Prediction:
 [153.31245 183.74153 181.53227 193.51079 143.74062]
90 Cost: 2.9745586 
Prediction:
 [153.3115  183.74207 181.53185 193.51126 143.74069]
100 Cost: 2.9730482 
Prediction:
 [153.31055 183.74265 181.53146 193.5118  143.74075]
110 Cost: 2.9715748 
Prediction:
 [153.30962 183.74324 181.5310

970 Cost: 2.8483005 
Prediction:
 [153.23367 183.78842 181.49902 193.55719 143.74277]
980 Cost: 2.8469408 
Prediction:
 [153.23285 183.7889  181.49867 193.5577  143.74274]
990 Cost: 2.8455434 
Prediction:
 [153.23203 183.78937 181.4983  193.55823 143.7427 ]
1000 Cost: 2.8441684 
Prediction:
 [153.23122 183.78984 181.49794 193.55875 143.74268]
1010 Cost: 2.8427901 
Prediction:
 [153.23041 183.79033 181.4976  193.55928 143.74265]
1020 Cost: 2.841399 
Prediction:
 [153.2296  183.79082 181.49725 193.55983 143.74263]
1030 Cost: 2.8400123 
Prediction:
 [153.22876 183.7913  181.4969  193.56035 143.7426 ]
1040 Cost: 2.8386414 
Prediction:
 [153.22797 183.79178 181.49655 193.56088 143.74257]
1050 Cost: 2.8372657 
Prediction:
 [153.22714 183.79225 181.49619 193.56139 143.74252]
1060 Cost: 2.8358753 
Prediction:
 [153.22635 183.79272 181.49585 193.56195 143.7425 ]
1070 Cost: 2.8345132 
Prediction:
 [153.22552 183.79321 181.4955  193.56245 143.74246]
1080 Cost: 2.8331294 
Prediction:
 [153.2247  1

1940 Cost: 2.7185872 
Prediction:
 [153.15987 183.83144 181.4667  193.60889 143.73593]
1950 Cost: 2.7172856 
Prediction:
 [153.15916 183.83185 181.46638 193.60942 143.73581]
1960 Cost: 2.7160063 
Prediction:
 [153.15845 183.83223 181.46606 193.60994 143.73569]
1970 Cost: 2.7146964 
Prediction:
 [153.15775 183.83264 181.46573 193.61047 143.73557]
1980 Cost: 2.7134087 
Prediction:
 [153.15704 183.83304 181.46542 193.61102 143.73546]
1990 Cost: 2.7121205 
Prediction:
 [153.15636 183.83345 181.46512 193.61157 143.73535]
2000 Cost: 2.710837 
Prediction:
 [153.15564 183.83385 181.46481 193.61212 143.73526]
